### PR TITLE
Merge in updated libraries from Cantaloup 5.0.6 and fix test failures

### PR DESCRIPTION
**Pull request by angelahuqing**
5.0.6 is merged into develop branch as well as replacing or removing tests/functions that aren't being used and causing failure.

### CODE REVIEW

**Comment by glenrobson** [comment]
Hi @angelahuqing, thank you for submitting this pull request and doing all of the work to bring in the changes. Are you able to make the Cantaloupe meeting later?

I've had a look at the code and there are a few changes which seem wider than just the library version update. Specificlly: 

 * What is the affect of removing UriCompliance?
https://github.com/cantaloupe-project/cantaloupe/pull/656/commits/25fa82259be976e7163a90a956e827c899a6a791
 * I can see you've removed [XMPElements](https://github.com/cantaloupe-project/cantaloupe/pull/656/commits/0d0af0db9ef87f77827e87ada8ceb82e8b14057d) and mention that it isn't used but I can see its used in the [delegates script](https://github.com/cantaloupe-project/cantaloupe/blob/21057cf72071840e2a984450bf8845c6e6490ec9/delegates.rb.sample#L358) which means some people might be relying on it. 
 * I can see you've also removed the s3 [multipart output stream](https://github.com/cantaloupe-project/cantaloupe/pull/656/commits/dbb014cd6a2c0f4ecfc56c3170113e5cb9374581) and related tests. Is this no longer needed?

I'm happy to close my pull request (#653) in favour of this one but just want to check we aren't removing needed functionality. Thanks

**Comment by angelahuqing** [comment]
Hi @glenrobson I think I may have missed the meeting, but if you let me know when the next one is, I can try and attend. To give you some more context on the changes I made, all of the changes came as a result of failing tests in the GA. Anything that I removed was because it was a direct cause of a failing test. I also cross-checked with the 5.0.6 release to see what hadn't been automatically merged and deduced from that what could be removed. For example

- [the multipart output stream](https://github.com/cantaloupe-project/cantaloupe/pull/656/commits/dbb014cd6a2c0f4ecfc56c3170113e5cb9374581) is no longer being used in 5.0.6 and was causing test failures which is why I removed it and replaced it with the function that is being used in 5.0.6 in the same instances. 5.0.6 and dev are now more in sync with one another because of it. 
- UriConpliance was also failing tests and isn't in 5.0.6 anymore and didn't seem necessary in dev
- I didn't realize the [XMPElements](https://github.com/cantaloupe-project/cantaloupe/pull/656/commits/0d0af0db9ef87f77827e87ada8ceb82e8b14057d) are being used in the delegate scripts. The XMPElements methods that I removed aren't in 5.0.6.

**Comment by glenrobson** [comment]
Ah I can see that the XMP Elements were added [here](https://github.com/cantaloupe-project/cantaloupe/commit/3ba2c979de713de962a6f9ab15975cb7d7b5a56b) to the develop branch. I can't see a related issue requesting this feature but useful to know its something new.

Also the multipart upload for s3 was added [here](https://github.com/cantaloupe-project/cantaloupe/commit/f3dddb09d8aabcc631f146438cace2c106cd6e6e) and we discussed in the meeting that this would help with large images that are cached.

Is there a way we could look at fixing the breaking tests for XMP and s3 without removing them?

**Comment by angelahuqing** [comment]
I think it's possible to fix the tests for XMP and s3. I didn't look into it too much because this PR was focused on getting the merge between dev and 5.0.6 done without failures so that the security issues would be fixed. I don't necessarily know if I will have the time to debug them, but I think someone theoretically could.

**Comment by angelahuqing** [comment]
@glenrobson will continue working on merging libraries from 5.0.6 in https://github.com/cantaloupe-project/cantaloupe/pull/668. As a result this PR will be closed and all future work will be done on that pull request.

**Pull request closed without merging**
