### PR TITLE
Fix/wrapped reads

### PR DESCRIPTION
**Pull request by adam-vessey**
#659 with what seems to be the expected exception wrapping in place?

### CODE REVIEW

**Comment by DiegoPino** [comment]
@adam-vessey @glenrobson Test on Ubuntu latest are failing bc docker-compose was replaced by docker compose. Will check on that later.
@adam-vessey also: the JPEG2000 workaround looks great, but wondering, will that not also fail (test are no problem anymore!) with EOF for jpegs and the other metadata classes updated here if corrupt files are encountered in the wild?

**Comment by adam-vessey** [comment]
@DiegoPino:

> will that not also fail [...] with EOF for jpegs and the other metadata functions

Yes, but it would've/should've been an issue previously, should whatever underlying stream throw a more general `IOException`. Kinda looks like the big difference here is that [`JPEG2000MetadataReaderTest`](https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/test/java/edu/illinois/library/cantaloupe/processor/codec/jpeg2000/JPEG2000MetadataReaderTest.java#L42) expects `SourceFormatException` to be thrown (which similar to `EOFException` is a more specific `IOException`), while it seems the other metadata readers deal with other `IOException`s when testing failures ([GIF](https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/test/java/edu/illinois/library/cantaloupe/processor/codec/gif/GIFMetadataReaderTest.java#L52) has `IOException` and `IllegalStateException` in various places, [JPEG](https://github.com/cantaloupe-project/cantaloupe/blob/develop/src/test/java/edu/illinois/library/cantaloupe/processor/codec/jpeg/JPEGMetadataReaderTest.java) only has `IOException` presently). Either way, thanks to polymorphism, more specific `IOException`s being thrown either way should satisfy those other tests which look for `IOException`s.

In terms of the actual problem being fixed, it should no longer enter the infinite loop when encountering the issue with reading described in #659

**Comment by DiegoPino** [comment]
@adam-vessey thanks for the clarification. That makes sense.

**Comment by adam-vessey** [comment]
Just rebased on top of the latest `develop` (at d34f2594b1257dd9795d61863bc8aa55340477a9), seeing #682 / #683 go in, which I understand should deal with the build of ubuntu-latest/graalvm to succeed? But now seeing the `windows-latest` stuff exploding?


```
Run docker-compose -f docker/Windows-JDK11/docker-compose.yml up --build --exit-code-from cantaloupe
docker-compose: D:\a\_temp\12ceb588-c64f-43d0-bfdc-bb63bdacde5b.ps1:2
Line |
   2 |  docker-compose -f docker/Windows-JDK11/docker-compose.yml up --build  …
     |  ~~~~~~~~~~~~~~
     | The term 'docker-compose' is not recognized as a name of a cmdlet, function, script file, or executable program.
     | Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Wondering if it might need the same treatment on the Windows side, `s/docker-compose/docker compose/`? Threw together https://github.com/cantaloupe-project/cantaloupe/pull/685 to give it a whirl.

**Comment by DiegoPino** [comment]
@adam-vessey yes, just seeing it. Everyday a new thing. Do you want to bring that change into this pull? I can also open another pull just for that and we go from there?( you rebase again?).  Also the ubuntu builds/tests sometimes fail because of how the Upload/Cache/S3 tests are build but I can restart them if that happens here.

**Comment by adam-vessey** [comment]
@DiegoPino: I've already got #685 going, just with the `docker compose` fix. Was thinking to rebase this again after it goes in, but am not opposed to rolling it together, if we want.

**Comment by jcoyne** [comment]
@adam-vessey Would you be able to rebase now?

**Comment by adam-vessey** [comment]
@jcoyne : Was already in the process of doing so. :P

**Comment by adam-vessey** [comment]
All green, woo!

**Review by DiegoPino — APPROVED** [review]
Good! all green

**Comment by DiegoPino** [comment]
@adam-vessey all good (and green) and approved, thanks so much! I will let others chime in and if nothing comes up I will be merging by tomorrow noon. Have a great day

**Review by DiegoPino — APPROVED** [review]

**Pull request merged**
