### PR TITLE
Add missing WebIdentityTokenFileCredentialsProvider for S3ClientBuilder to allow use within EKS IRSA scenario

### PR DESCRIPTION
**Pull request by scottaubrey**
Related to https://github.com/cantaloupe-project/cantaloupe/issues/637

I'm not a Java developer, so I'm not sure if this is right in any way, other than we do build with this patch and run it in production successfully. I welcome anything I can do to make this acceptable.

### CODE REVIEW

**Comment by nlisgo** [comment]
This looks like a great addition. Thanks for the contribution!

**Comment by glenrobson** [comment]
Closing in favour of https://github.com/cantaloupe-project/cantaloupe/pull/638 which applise the change to the develop branch.

**Comment by nlisgo** [comment]
@glenrobson your comment references this issue. Could you reference the correct issue so we can access it?

**Comment by scottaubrey** [comment]
https://github.com/cantaloupe-project/cantaloupe/pull/701

**Pull request closed without merging**
