### PR TITLE
grok: upgrade to version v7.6.5

### PR DESCRIPTION
**Pull request by boxerab**
7.6.5 fixes a number of security bugs and crashes relative to 7.6.1

### CODE REVIEW

**Comment by boxerab** [comment]
hi @adolski , is there any way of getting Perl 5.32 installed on the graalvm VM ?

**Comment by adolski** [comment]
I don't understand why it's complaining about perl in the GraalVM image, but not in any of the other images that are based on the same `ubuntu:latest` image. They all appear to have perl 5.30 installed.

**Comment by boxerab** [comment]
Yes, that is odd. I looked into my debian packages, and they are built against Perl 5.32 .so binaries, but if this is a problem, it should appear in all VMs as you mentioned.

**Comment by boxerab** [comment]
@adolski I re-built on a system with perl 5.30. Now ready to merge.

**Comment by boxerab** [comment]
Thanks!

**Pull request merged**
