### PR TITLE
Upgrade to the newest non-LTS openjdk

### PR DESCRIPTION
**Pull request by jcoyne**
18 -> 22

### CODE REVIEW

**Comment by glenrobson** [comment]
Should the docker compose files be called `docker-compose.yml` rather than `compose.yaml` for consistency?

**Comment by jcoyne** [comment]
@glenrobson I was migrating to the documented standard, which is `compose.yaml` https://docs.docker.com/compose/gettingstarted/#step-2-define-services-in-a-compose-file

**Comment by glenrobson** [comment]
Thanks, I hadn't realised the recomended name had changed. I think there is still some insconsitency though:

* docker/Linux-GraalVM20/docker-compose.yml
* docker/Linux-JDK17/compose.yml
* docker/Linux-JDK21/compose.yml
* docker/Linux-JDK22/compose.yaml
* docker/Windows-JDK11/docker-compose.yml
* docker/Windows-JDK17/compose.yml
* docker/Windows-JDK21/compose.yml
* docker/Windows-JDK22/compose.yaml

**Comment by jcoyne** [comment]
@glenrobson fixed in https://github.com/cantaloupe-project/cantaloupe/pull/696.  And JDK11 is EOL, so I'm not going to bother with that one. I'll make a pr to remove it once https://github.com/cantaloupe-project/cantaloupe/pull/693 is merged.

**Review by glenrobson — APPROVED** [review]

**Pull request merged**
